# Generated by Django 4.0.3 on 2022-03-22 11:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='image'),
            preserve_default=False,
        ),
    ]
