# Generated by Django 4.0.3 on 2022-03-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
